# Generated by Django 2.2 on 2020-03-04 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_auto_20200304_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='livetime',
            field=models.IntegerField(choices=[(0, '无期限'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3')], default=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 15, 58, 17, 900861)),
        ),
    ]
