# Generated by Django 2.2 on 2020-03-04 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0003_auto_20200304_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 16, 6, 34, 766493)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(3, '学生'), (2, '老师'), (1, '管理员')], default=0),
        ),
    ]
