# Generated by Django 2.2 on 2020-03-04 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0005_auto_20200304_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 16, 44, 20, 770666)),
        ),
        migrations.AlterField(
            model_name='user',
            name='takeschoolyear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
