# Generated by Django 2.2 on 2020-03-05 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0009_auto_20200305_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 19, 49, 13, 641581)),
        ),
    ]
