# Generated by Django 2.2 on 2020-03-06 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0015_auto_20200306_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 18, 27, 43, 202856)),
        ),
    ]
