# Generated by Django 2.2 on 2020-03-06 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0016_auto_20200306_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 18, 29, 33, 600686)),
        ),
    ]
