# Generated by Django 2.2 on 2020-03-06 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0017_auto_20200306_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 19, 23, 32, 620686)),
        ),
    ]
