# Generated by Django 2.2 on 2020-03-07 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0018_auto_20200306_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idcard',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 0, 29, 36, 270324)),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='weixin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
