# Generated by Django 2.2 on 2020-03-07 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0019_auto_20200307_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 15, 3, 56, 540171)),
        ),
        migrations.AlterField(
            model_name='user',
            name='schoolclass',
            field=models.IntegerField(default=10000),
        ),
    ]
