# Generated by Django 2.2 on 2020-03-07 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0020_auto_20200307_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 16, 11, 18, 620534)),
        ),
    ]
