# Generated by Django 2.2 on 2020-03-07 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0021_auto_20200307_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 20, 21, 11, 97439)),
        ),
    ]
