# Generated by Django 2.2 on 2020-03-08 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0025_auto_20200308_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 18, 46, 14, 109387)),
        ),
    ]
