# Generated by Django 2.2 on 2020-05-18 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0027_auto_20200308_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 20, 12, 2, 977980)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '在读'), (1, '休学'), (2, '在职'), (3, '离职')], default=0),
        ),
    ]
