# Generated by Django 2.2 on 2020-05-18 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0029_auto_20200518_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 21, 10, 42, 710701)),
        ),
    ]
