# Generated by Django 2.2 on 2020-03-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publishtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
