# Generated by Django 2.2 on 2020-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200305_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchfile',
            old_name='news',
            new_name='research',
        ),
        migrations.AddField(
            model_name='newsfile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newspic',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='researchfile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='researchpic',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
