# Generated by Django 2.2 on 2020-03-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_research_publishtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='tel',
            field=models.CharField(default='', max_length=12),
        ),
    ]
