# Generated by Django 2.2 on 2020-03-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_lost_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpic',
            old_name='news',
            new_name='research',
        ),
    ]
