# Generated by Django 2.2 on 2020-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200307_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='endtime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='starttime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
