# Generated by Django 2.2 on 2020-03-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200308_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='read_type',
            field=models.IntegerField(choices=[(0, '选修'), (1, '必修')], default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='total',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.IntegerField(choices=[(0, '公共课'), (1, '实践课'), (2, '通识课')], default=0),
        ),
    ]
