# Generated by Django 2.2 on 2020-03-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200308_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
