# Generated by Django 2.2 on 2020-05-18 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0015_auto_20200308_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, '艺术类'), (1, '学术科技类'), (2, '体育类'), (3, '其他')])),
                ('endtime', models.DateField()),
                ('status', models.IntegerField(choices=[(0, '比赛进行'), (1, '比赛结束')], default=0)),
                ('team_people', models.IntegerField(default=20)),
                ('host', models.CharField(max_length=150)),
                ('advice_team', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pic', models.ImageField(blank=True, max_length=1000, null=True, upload_to='match/pic/%Y/%m/')),
                ('enclosure', models.FileField(blank=True, null=True, upload_to='match/file/%Y/%m/')),
                ('check_team_num', models.IntegerField(default=0)),
                ('sum_team_num', models.IntegerField(default=0)),
                ('result', models.FileField(blank=True, null=True, upload_to='match/file/%Y/%m/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, '队长'), (1, '队员'), (2, '指导老师')], default=0)),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '未通过')], default=0)),
                ('name', models.CharField(max_length=100)),
                ('no_pass', models.CharField(max_length=150)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='school.Match')),
                ('students', models.ManyToManyField(through='school.Team_Students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team_students',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teams'),
        ),
    ]
