# Generated by Django 2.2 on 2020-05-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20200518_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='enclosure',
        ),
        migrations.AddField(
            model_name='match',
            name='publishtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_people',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Match_Enclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enclosure', models.FileField(blank=True, null=True, upload_to='match/file/%Y/%m/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enclosure', to='school.Match')),
            ],
        ),
    ]
