# Generated by Django 2.2 on 2020-05-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20200518_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_enclosure',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
