# Generated by Django 2.2 on 2020-05-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20200519_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_students',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
